export type WorkProject = {
  slug: string;
  title: string;
  shortTitle: string;
  year: string;
  category: string;
  group: "CubeIT Labs" | "Client Delivery";
  services: string[];
  cover: string;
  width: number;
  height: number;
  description: string;
  challenge: string;
  solution: string;
  role: string;
  technologies: string[];
  outcome?: string;
  accent?: "blue" | "orange";
};

export const workProjects: WorkProject[] = [
  {
    slug: "mizan",
    title: "MIZAN",
    shortTitle: "MIZAN",
    year: "2026",
    category: "AI Legal Intelligence",
    group: "CubeIT Labs",
    services: ["AI product", "Legal workflows", "Product design"],
    cover: "/projects/mizan-legal.jpg",
    width: 1400,
    height: 933,
    description: "An AI legal case management system for drafting, evidence handling, hearing schedules and secure matter workflows.",
    challenge: "Legal teams need one dependable system for documents, deadlines, evidence and client communication without adding more operational noise.",
    solution: "CubeIT shaped the platform around case work: AI-assisted drafting, organized matter context, evidence vaults and deadline-aware workflows.",
    role: "Product strategy, UX architecture, full-stack engineering and AI workflow design.",
    technologies: ["Python", "React", "Postgres"],
    outcome: "A unified legal operating system concept built for serious case work.",
  },
  {
    slug: "shopiq",
    title: "ShopIQ",
    shortTitle: "ShopIQ",
    year: "2026",
    category: "Retail Intelligence",
    group: "CubeIT Labs",
    services: ["Retail platform", "Analytics", "Inventory systems"],
    cover: "/projects/shopiq.jpg",
    width: 1400,
    height: 1786,
    description: "A retail and inventory intelligence platform for live stock movement, branch performance and demand visibility.",
    challenge: "Retail operators often see inventory too late and performance too separately to make confident daily decisions.",
    solution: "The product connects stock movement, demand signals and branch-level performance into a calmer operational view.",
    role: "Product architecture, interface design and analytics workflow planning.",
    technologies: ["Next.js", "Node.js", "Postgres"],
    outcome: "A clearer way for retail teams to understand what is moving and what needs attention.",
  },
  {
    slug: "clinova",
    title: "Clinova",
    shortTitle: "Clinova",
    year: "2026",
    category: "Healthcare Operations",
    group: "CubeIT Labs",
    services: ["Healthcare platform", "Patient journey", "Operational UX"],
    cover: "/projects/clinova.jpg",
    width: 1400,
    height: 933,
    description: "A connected clinic operations platform spanning appointments, medical records, billing and clinical documentation.",
    challenge: "Healthcare teams need patient information and administrative work to move together without making the experience feel heavier.",
    solution: "Clinova organizes the patient journey around the moments clinics repeat every day: booking, records, billing and care documentation.",
    role: "UX systems, product interface and platform planning.",
    technologies: ["React", "TypeScript", "Docker"],
    outcome: "A calmer operational foundation for clinics and care teams.",
  },
  {
    slug: "documind",
    title: "DocuMind",
    shortTitle: "DocuMind",
    year: "2026",
    category: "AI Document Intelligence",
    group: "CubeIT Labs",
    services: ["Document AI", "Workflow automation", "Search"],
    cover: "/projects/documind.jpg",
    width: 1400,
    height: 933,
    description: "An AI document intelligence platform for OCR, semantic search, document chat and approval workflows.",
    challenge: "Document-heavy teams lose time when information is captured in one place, reviewed in another and searched manually later.",
    solution: "DocuMind brings capture, search, approval and AI-assisted understanding into one document workflow.",
    role: "AI workflow design, product UX and full-stack platform planning.",
    technologies: ["Python", "Next.js", "Docker"],
    outcome: "A focused platform direction for turning document archives into usable business knowledge.",
  },
  {
    slug: "buildgrid",
    title: "BuildGrid",
    shortTitle: "BuildGrid",
    year: "2026",
    category: "Construction Control",
    group: "CubeIT Labs",
    services: ["Construction software", "Field operations", "Dashboards"],
    cover: "/projects/buildgrid.jpg",
    width: 1400,
    height: 788,
    description: "A construction project control platform for field progress, budget movement, procurement and contractor activity.",
    challenge: "Construction teams need field updates and project controls to stay connected while work is changing on site.",
    solution: "BuildGrid organizes site progress, procurement and budget signals into one project control surface.",
    role: "Operational product strategy, UX architecture and engineering planning.",
    technologies: ["TypeScript", "Node.js", "Postgres"],
    outcome: "A more visible operating layer for complex construction work.",
  },
  {
    slug: "supportiq",
    title: "SupportIQ",
    shortTitle: "SupportIQ",
    year: "2026",
    category: "AI Support Infrastructure",
    group: "CubeIT Labs",
    services: ["AI support", "Knowledge systems", "Internal tools"],
    cover: "/projects/supportiq.jpg",
    width: 1400,
    height: 1050,
    description: "An AI support and ticket intelligence concept for routing, knowledge graphs and agent assistance.",
    challenge: "Support teams need faster context without losing the human judgment required for sensitive customer issues.",
    solution: "SupportIQ connects tickets, knowledge and routing logic so support teams can respond with more context and less searching.",
    role: "Product strategy, AI workflow planning and interface design.",
    technologies: ["React", "Python", "Tailwind"],
    outcome: "A practical AI layer for support teams that need clarity, not more tabs.",
  },
  {
    slug: "darabyte",
    title: "Darabyte",
    shortTitle: "Darabyte",
    year: "2026",
    category: "Technology Company Website",
    group: "Client Delivery",
    services: ["Brand website", "Service architecture", "Lead generation"],
    cover: "/client-work/darabyte.png",
    width: 1905,
    height: 851,
    description: "A confident corporate platform positioning Darabyte around intelligent transformation, ERP, automation and custom software.",
    challenge: "A broad technology offering needed a clearer digital front door and a more organized service story.",
    solution: "CubeIT shaped the website around transformation themes, service hierarchy and a direct path into project conversation.",
    role: "Art direction, responsive web design and frontend delivery.",
    technologies: ["Next.js", "Responsive UI", "Brand system"],
    outcome: "A clearer digital front door for a broad technology offering.",
  },
  {
    slug: "asab-erp",
    title: "ASAB ERP",
    shortTitle: "ASAB ERP",
    year: "2026",
    category: "Maritime SaaS Website",
    group: "Client Delivery",
    services: ["SaaS website", "ERP modules", "AI positioning"],
    cover: "/client-work/asab-erp.png",
    width: 1777,
    height: 857,
    description: "A product-led website for a maritime operations platform spanning vessels, suppliers, agents, managers and ports.",
    challenge: "A complex maritime platform needed to explain many operational modules without overwhelming visitors.",
    solution: "The experience breaks platform complexity into calm, product-led sections with a clearer story for each operational audience.",
    role: "Product storytelling, visual system and responsive website implementation.",
    technologies: ["Next.js", "SaaS UX", "Content architecture"],
    outcome: "Complex platform capabilities organized into a calm product story.",
  },
  {
    slug: "jaunt-solutions",
    title: "Jaunt Solutions",
    shortTitle: "Jaunt",
    year: "2026",
    category: "Digital Transformation Website",
    group: "Client Delivery",
    services: ["Corporate UX", "Service discovery", "Art direction"],
    cover: "/client-work/jaunt-solutions.png",
    width: 1776,
    height: 848,
    description: "A cinematic, service-led experience that frames Jaunt as a transformation partner across technology, strategy and industry delivery.",
    challenge: "The brand needed to communicate capability and momentum while keeping the visitor pathway direct.",
    solution: "CubeIT built a clearer service narrative supported by refined visual hierarchy and strong conversion moments.",
    role: "Experience design, frontend implementation and service storytelling.",
    technologies: ["Responsive web", "Motion design", "Content system"],
    outcome: "A stronger visual identity with an immediate project pathway.",
  },
  {
    slug: "dynamic-innovations",
    title: "Dynamic Innovations",
    shortTitle: "Dynamic",
    year: "2026",
    category: "Corporate Transformation Website",
    group: "Client Delivery",
    services: ["Brand system", "Responsive UI", "Conversion design"],
    cover: "/client-work/dynamic-innovations.png",
    width: 1767,
    height: 867,
    description: "A polished corporate presence built around intentional innovation, modern services and a more distinctive point of view.",
    challenge: "The company needed a more refined digital presence to support enterprise transformation conversations.",
    solution: "The website uses a cleaner narrative, stronger visual rhythm and clearer action points across the experience.",
    role: "Visual direction, UX design and frontend delivery.",
    technologies: ["Responsive web", "Design system", "Frontend"],
    outcome: "A refined brand story with a focused conversion journey.",
  },
  {
    slug: "dea-modern",
    title: "DEA Modern",
    shortTitle: "DEA II",
    year: "2026",
    category: "Industrial Website Redesign",
    group: "Client Delivery",
    services: ["Website redesign", "Industrial UX", "Returning client"],
    cover: "/client-work/dea-modern.png",
    width: 1777,
    height: 855,
    description: "DEA returned to CubeIT for a more modern website that communicates industrial scale, energy technology and engineering authority.",
    challenge: "The next chapter needed to feel more current while still respecting DEA's industrial and engineering foundation.",
    solution: "CubeIT refreshed the experience with stronger hierarchy, more modern visual language and a clearer service presentation.",
    role: "Redesign strategy, visual design and frontend implementation.",
    technologies: ["Responsive UI", "Brand refresh", "Frontend"],
    outcome: "A returning client, reintroduced for a new digital era.",
    accent: "orange",
  },
  {
    slug: "dea-original",
    title: "DEA Original",
    shortTitle: "DEA I",
    year: "2025",
    category: "Engineering Company Website",
    group: "Client Delivery",
    services: ["Original website", "Company profile", "Foundation"],
    cover: "/client-work/dea-original.png",
    width: 1875,
    height: 862,
    description: "The earlier DEA website presented the company's engineering expertise, background and service scope clearly.",
    challenge: "DEA needed a dependable first digital chapter that could communicate its core engineering profile.",
    solution: "CubeIT delivered a clear company website structured around capability, credibility and service information.",
    role: "Website design, frontend implementation and content structure.",
    technologies: ["Responsive website", "Content architecture", "Frontend"],
    outcome: "A dependable first digital chapter that met the brief of its time.",
  },
];

export function getWorkProject(slug: string) {
  return workProjects.find((project) => project.slug === slug);
}

export function getNextWorkProject(slug: string) {
  const index = workProjects.findIndex((project) => project.slug === slug);
  return workProjects[(index + 1 + workProjects.length) % workProjects.length];
}
